---
book_repo: docs-book
layout_repo: docs-layout

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

pcf_header: &local_pcf
  use_local_header: true
  latest_stable_version:
  changelog_href: '#'
  local_header_img: /images/cloud_rings.png
  local_header_title: Pivotal Distribution of OpenJDK
public_host: hello

sections:
  - repository:
      name: docs-content
    directory: pivotal-distribution-openjdk
    subnav_template: pivotal-distribution-openjdk_subnav.erb       

template_variables:                             # optional

book_title: Partner Services Template
book_repo: docs-book
layout_repo: docs-layout
